version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "action/dependency"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "action/dependency"
    schedule:
      interval: "weekly"
    groups:
      go:
        patterns:
          - "*"
