package alert

import alertclient "github.com/grafana/gcx/client/alert"

// Alert rule state constants. The Grafana alerting API only returns these three states.
const (
	StateFiring   = alertclient.StateFiring
	StatePending  = alertclient.StatePending
	StateInactive = alertclient.StateInactive
)

// The alert rules API wire types live in the public client/alert package. They
// carry no resource-adapter methods, so the CLI uses them directly rather than
// keeping a second copy.
type (
	// RulesResponse is the response from /api/prometheus/grafana/api/v1/rules.
	RulesResponse = alertclient.RulesResponse
	// RulesData contains the groups and totals from the rules response.
	RulesData = alertclient.RulesData
	// RuleGroup represents an alert rule group.
	RuleGroup = alertclient.RuleGroup
	// RuleStatus represents an alert rule with its current status.
	RuleStatus = alertclient.RuleStatus
	// AlertInstance represents a currently active or pending alert generated by a rule.
	AlertInstance = alertclient.AlertInstance
	// NotificationSettings contains notification configuration for an alert rule.
	NotificationSettings = alertclient.NotificationSettings
)
