name: 🚀 Enhancement
description: Suggest an improvement to existing functionality
title: 🚀 Enhancement
labels: ["action/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Found a way to make something better? Tell us about your idea.

  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: Describe your idea for improving an existing feature. Try and include what happens today, what you'd like to change, and why it would be better.
      placeholder: |
        The `gcx resources push` command currently processes all resources sequentially.
        When pushing 100s of dashboards, it takes a long time to complete.
        There's a --max-concurrent flag, but it doesn't seem to have much effect.

        The push command should better utilize concurrency. Maybe:
        - Increase default --max-concurrent value, or have it configurable
        - Add optional progress indicators showing which resources are being processed

        We could speed up our CD pipeline with this improvement.
    validations:
      required: true
