name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: read

# Allow only one concurrent release, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow them to complete.
concurrency:
  group: "releases"
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write # to push new branches
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Set release notes
        run: |
          delimiter="$(openssl rand -hex 16)"
          {
            echo "RELEASE_NOTES<<${delimiter}"
            cat .release-notes.md
            echo "${delimiter}"
          } >> "$GITHUB_ENV"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}

